### PR TITLE
ENH: Overload vnl_real and vnl_imag

### PR DESCRIPTION
**Pull request by DVigneault**
`vnl_real` and `vnl_imag` are overloaded for additional matrix types.  Unit tests are provided covering the overloads.

### CODE REVIEW

**Comment by DVigneault** [comment]
One test failed on clang (g++ passed):

Error:
The following tests FAILED:
	590 - rgrl_estimator (Failed)

I built with g++.  Any reason to believe this is related to the patch?  If so I can try building with clang tomorrow and see if I can reproduce the error.

**Comment by DVigneault** [comment]
Just rebuilt and tested with clang, and `rgrl_estimator` passes--the following fail, which you all are already aware of.

	713 - bocl_test_global_io_bandwidth (SEGFAULT)
	714 - bocl_test_kernel (SEGFAULT)
	715 - bocl_test_local_mem_access (SEGFAULT)

**Comment by hjmjohnson** [comment]
@DVigneault Please ignore the "rgrl_estimator"  .... See #96 

@yanggehua   --- This failing test is distracting and slowing down other development efforts.  Is this something that you will be able to address soon?  ... Thanks,

**Comment by dstoup** [comment]
This branch looks good to me. Any fundamental objections from the serious vnl users?

**Comment by hjmjohnson** [comment]
These added function signatures provide a natural API feature set.

The API comes with expanded testing.

My vote is to approve.

**Comment by dstoup** [comment]
Thanks Hans!

**Pull request merged**
