### PR TITLE
Breg3d ekf camera optimizer test fix

### PR DESCRIPTION
**Pull request by decrispell**
Fix some tests failing due to SEGFAULT on MacOS

### CODE REVIEW

**Comment by decrispell** [comment]
Note that the last commit (87c46de) is the one that actually fixed the segfault. The others are cleanup.

**Comment by dstoup** [comment]
Thanks @decrispell, does this patch fix a dashboard test, or just something you've observed?

**Comment by dstoup** [comment]
... sorry, I see my answer in the title :(

**Comment by decrispell** [comment]
Yeah, I originally was just trying to fix the test referenced in the title, but the fix actually seems to have fixed many of the segfault failures seen here:  https://open.cdash.org/viewTest.php?onlyfailed&buildid=4137668

**Comment by dstoup** [comment]
This is excellent, thank you! It will be great to see some green on the dashboards. I cycled it through my mac dashboards just fine and it knocked out half of the issues, ready to go.

**Pull request merged**
