### PR TITLE
ENH: Replace literal zero with VXL_NULLPTR

### PR DESCRIPTION
**Pull request by DVigneault**
This patch makes use of Hans's recent addition, `VXL_NULLPTR`, to cut down on a few `warning: zero as null pointer constant` warnings.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@DVigneault Fabulous.  Did you do this by hand or use clang-tidy?

Will merge if clean build occurs.

**Comment by DVigneault** [comment]
@hjmjohnson I did this by hand--will check out clang-tidy this weekend, it looks really cool.

**Comment by hjmjohnson** [comment]
David,

The attached is a rough script/notes on how to build llvm in a unix environment.

Hans

**Comment by DVigneault** [comment]
Hans--

The attachment didn't make it through--would you mind resending?  Excited
to take advantage of this tool!

Best,

--Davis

**Pull request merged**
