### PR TITLE
Simplify logic for c++11 in class initializations

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@decrispell Can you please try this patch out?  I'm not sure it fixes the problem, but hopefully it will make it easier to identify what is going wrong.

**Comment by decrispell** [comment]
Thanks for looking into this @hjmjohnson .  The build seems to have made it past the vnl errors I was seeing before.  There are now similar looking errors, this time in vipl (first few copied below).

```
In file included from /home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter.h:410:0,
                 from /home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter_2d.h:10,
                 from /home/dec/vxl/src/contrib/tbl/vipl/vipl_threshold.h:41,
                 from /home/dec/vxl/src/contrib/tbl/vipl/examples/example1_threshold.cxx:25:
/home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter.hxx:17:90: error: redeclaration ‘vipl_filter<ImgIn, ImgOut, DataIn, DataOut, Arity, PixelItr>::Not_Ready’ differs in ‘constexpr’
 VXL_CONSTEXPR VIPL_FILTER_STATE vipl_filter<ImgIn,ImgOut,DataIn,DataOut,Arity,PixelItr>::Not_Ready VCL_STATIC_CONST_INIT_INT_DEFN( 0 );
                                                                                          ^
In file included from /home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter_2d.h:10:0,
                 from /home/dec/vxl/src/contrib/tbl/vipl/vipl_threshold.h:41,
                 from /home/dec/vxl/src/contrib/tbl/vipl/examples/example1_threshold.cxx:25:
/home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter.h:95:34: error: from previous declaration ‘vipl_filter<ImgIn, ImgOut, DataIn, DataOut, Arity, PixelItr>::Not_Ready’
   static const VIPL_FILTER_STATE Not_Ready      VCL_STATIC_CONST_INIT_INT_DECL(0);
                                  ^
In file included from /home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter.h:410:0,
                 from /home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter_2d.h:10,
                 from /home/dec/vxl/src/contrib/tbl/vipl/vipl_threshold.h:41,
                 from /home/dec/vxl/src/contrib/tbl/vipl/examples/example1_threshold.cxx:25:
/home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter.hxx:17:90: error: ‘vipl_filter<ImgIn, ImgOut, DataIn, DataOut, Arity, PixelItr>::Not_Ready’ declared ‘constexpr’ outside its class
 VXL_CONSTEXPR VIPL_FILTER_STATE vipl_filter<ImgIn,ImgOut,DataIn,DataOut,Arity,PixelItr>::Not_Ready VCL_STATIC_CONST_INIT_INT_DEFN( 0 );
                                                                                          ^
/home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter.hxx:17:90: error: declaration of ‘const VIPL_FILTER_STATE vipl_filter<ImgIn, ImgOut, DataIn, DataOut, Arity, PixelItr>::Not_Ready’ outside of class is not definition [-fpermissive]
In file included from /home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter.h:410:0,
                 from /home/dec/vxl/src/contrib/tbl/vipl/filter/vipl_filter_2d.h:10,
                 from /home/dec/vxl/src/contrib/tbl/vipl/vipl_threshold.h:41,
                 from /home/dec/vxl/src/contrib/tbl/vipl/examples/example1_threshold.cxx:25:
```

**Comment by hjmjohnson** [comment]
GREAT! We are getting close then.

I just missed converting those to be consistent like I did in the other cases.  The same solution should work there as well.

Branch updated a few minutes ago.  

Thank you for testing. Please let me know how this patch set works out.

Hans

**Comment by decrispell** [comment]
Looks good!  This version compiles for me with no errors.

**Comment by hjmjohnson** [comment]
:) Yeah!  Thank you for your help.  I’ll merge once travis-ci completes.

Hans

**Comment by decrispell** [comment]
Great, Thanks again.  I'll leave the -std=c++11 flag in my dashboard build.

**Comment by hjmjohnson** [comment]
@decrispell Merged!

**Pull request merged**
