### PR TITLE
TSan issues

### PR DESCRIPTION
**Pull request by seanm**
## PR Checklist

-  Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
-  Makes design changes to existing vxl/core\* API that requires semantic versioning increase

-  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
-  Adds tests and baseline comparison (quantitative).
-  Adds Documentation.

### CODE REVIEW

**Comment by seanm** [comment]
@hjmjohnson @thewtex @dzenanz

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
```text
/vxl/core/vnl/algo/vnl_svd.hxx:209:39: error: 'atomic_flag_test_and_set' is not a member of 'std'
 inline bool vnl_svn_warned() { return std::atomic_flag_test_and_set(&w); }
```

**Comment by dzenanz** [comment]
Probably needs `#include <atomic>`.

**Comment by seanm** [comment]
> Probably needs `#include <atomic>`.

Doh! Fixed.

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
I don't have write permission here, somebody else will have to merge.

**Review by hjmjohnson — APPROVED** [review]

**Comment by seanm** [comment]
There are 3 other tests that fail under ASan:

- vil_test_save_load_image : related to TIFF, but I gave up, the pointer arithmetic is too gnarly
- vil_test_4_plane_tiff : as above
- vpgl_algo_test_rational_adjust : also gnarly code, machine converted from fortran and so hard to decipher

**Comment by hjmjohnson** [comment]
@seanm I don't think those will affect ITK, so I don't think the ITK team will be working on them.  I am not sure which group uses those functions, but perhaps that team could address the issues.

**Comment by seanm** [comment]
The `vpgl_algo_test_rational_adjust` failure I think impacts ITK, because the bug is in `vnl_levenberg_marquardt.cxx` which I believe ITK uses, doesn't it?

**Comment by seanm** [comment]
I created an issue: https://github.com/vxl/vxl/issues/858

**Pull request merged**
