### PR TITLE
Turn off warning filled portions of vxl

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by decrispell** [comment]
Personally, the one component of vxl that is most valuable to me is vpgl - I have not found camera modeling of comparable quality and diversity in any other public library.  Turning off vgl will also turn off vpgl, so I am opposed to that change.

**Comment by hjmjohnson** [comment]
@decrispell Will you please make the dashboards pass then?  

Currently, we can't even build VXL with this broken portion of the turned on.  That means that by default, VXL doesn't even build on our testing environments.

[ 88%] Building CXX object core/vgl/io/tests/CMakeFiles/vgl_io_test_all.dir/test_point_2d_io.cxx.o
/home/travis/build/vxl/vxl/core/vgl/io/tests/test_point_2d_io.cxx:19:17: error: no matching constructor for initialization of 'std::ofstream' (aka 'basic_ofstream<char>')
  std::ofstream t_out(point_with_spaces);
                ^     ~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/fstream:640:7: note: candidate constructor not viable: no known conversion from 'std::string' (aka 'basic_string<char>') to 'const char *' for 1st argument
      basic_ofstream(const char* __s,
      ^
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/fstream.tcc:968:25: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::string' (aka 'basic_string<char>') to 'const std::basic_ofstream<char>' for 1st argument
  extern template class basic_ofstream<char>;
                        ^
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/fstream:625:7: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
      basic_ofstream(): __ostream_type(), _M_filebuf()
      ^
/home/travis/build/vxl/vxl/core/vgl/io/tests/test_point_2d_io.cxx:22:17: error: no matching constructor for initialization of 'std::ifstream' (aka 'basic_ifstream<char>')
  std::ifstream t_in(point_with_spaces);
                ^    ~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/fstream:467:7: note: candidate constructor not viable: no known conversion from 'std::string' (aka 'basic_string<char>') to 'const char *' for 1st argument
      basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
      ^
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/fstream.tcc:967:25: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::string' (aka 'basic_string<char>') to 'const std::basic_ifstream<char>' for 1st argument
  extern template class basic_ifstream<char>;

Additonally, 


The following tests FAILED:
	306 - vgl_io_test_point_3d_io (Not Run)
	307 - vgl_io_test_homg_point_1d_io (Not Run)
	308 - vgl_io_test_homg_point_2d_io (Not Run)
	309 - vgl_io_test_homg_point_3d_io (Not Run)
	310 - vgl_io_test_vector_2d_io (Not Run)
	311 - vgl_io_test_vector_3d_io (Not Run)
	312 - vgl_io_test_line_2d_io (Not Run)
	313 - vgl_io_test_line_3d_2_points_io (Not Run)
	314 - vgl_io_test_line_segment_2d_io (Not Run)
	315 - vgl_io_test_line_segment_3d_io (Not Run)
	316 - vgl_io_test_homg_line_2d_io (Not Run)
	317 - vgl_io_test_homg_line_3d_2_points_io (Not Run)
	318 - vgl_io_test_homg_plane_3d_io (Not Run)
	319 - vgl_io_test_conic_io (Not Run)
	320 - vgl_io_test_box_2d_io (Not Run)
	321 - vgl_io_test_box_3d_io (Not Run)
	322 - vgl_io_test_plane_3d_io (Not Run)
	323 - vgl_io_test_polygon_io (Not Run)
	324 - vgl_io_golden_test (Not Run)
	325 - vgl_test_xio (Not Run)
	326 - vil_io_test_memory_chunk_io (Not Run)
	327 - vil_io_test_image_view_io (Not Run)
	328 - vcsl_test_meter (Not Run)
	329 - vcsl_test_radian (Not Run)
	330 - vcsl_test_degree (Not Run)
	331 - vcsl_test_cartesian_2d (Not Run)
	332 - vcsl_test_cartesian_3d (Not Run)
	333 - vcsl_test_polar (Not Run)
	334 - vcsl_test_cylindrical (Not Run)
	335 - vcsl_test_spherical (Not Run)
	336 - vcsl_test_transformation_graph (Not Run)
	337 - vcsl_test_composition (Not Run)
	338 - vcsl_test_scale (Not Run)
	339 - vcsl_test_translation (Not Run)
	340 - vcsl_test_rotation (Not Run)
	341 - vcsl_test_displacement (Not Run)
	342 - vpgl_test_proj_camera (Not Run)
	343 - vpgl_test_perspective_camera (Not Run)
	344 - test_perspective_camera_decomposition (Not Run)
	345 - vpgl_test_affine_camera (Not Run)
	346 - vpgl_test_calibration_matrix (Not Run)
	347 - vpgl_test_poly_radial_distortion (Not Run)
	348 - vpgl_test_fundamental_matrix (Not Run)
	349 - vpgl_test_essential_matrix (Not Run)
	350 - vpgl_test_rational_camera (Not Run)
	351 - vpgl_test_local_rational_camera (Not Run)
	352 - vpgl_test_generic_camera (Not Run)
	353 - vpgl_test_lvcs (Not Run)
	354 - vpgl_algo_test_backproject_dem (Not Run)
	355 - vpgl_algo_test_camera_compute (Not Run)
	356 - vpgl_algo_test_camera_convert (Not Run)
	357 - vpgl_algo_test_optimize_camera (Not Run)
	358 - vpgl_algo_test_fm_compute (Not Run)
	359 - vpgl_algo_test_rational_adjust_onept (Not Run)
	360 - vpgl_algo_test_rational_adjust (Not Run)
	361 - vpgl_algo_test_lens_warp_mapper (Not Run)
	362 - vpgl_algo_test_backproject (Not Run)
	363 - vpgl_algo_test_ray (Not Run)
	364 - vpgl_algo_test_ray_intersect (Not Run)
	365 - vpgl_algo_test_ortho_procrustes (Not Run)
	366 - vpgl_algo_test_em_compute_5_point (Not Run)
	367 - vpgl_algo_test_triangulate (Not Run)
	368 - vpgl_algo_test_bundle_adjust (Not Run)
	369 - vpgl_algo_test_ba_fixed_k_lsqr (Not Run)
	370 - vpgl_algo_test_ba_shared_k_lsqr (Not Run)
	371 - vpgl_algo_test_affine_rect (Not Run)
	372 - vpgl_test_lvcs_io (Not Run)
	373 - vpgl_test_camera_io (Not Run)
	374 - vpgl_test_proj_camera_io (Not Run)
	375 - vpgl_test_perspective_camera_io (Not Run)
	376 - vpgl_test_affine_camera_io (Not Run)
	377 - vpgl_test_rational_camera_io (Not Run)
	378 - vpgl_test_local_rational_camera_io (Not Run)
	379 - testlib_assert (Not Run)
	380 - testlib_macros (Not Run)
	381 - testlib_args (Not Run)
	382 - testlib_root_dir (Not Run)
	383 - testlib_all (Not Run)
	384 - testlib_test_link (Not Run)
Errors while running CTest


COMP: Turn off long time failing test

These 3 tests have been failing for a long time without resolution.
162 - vgl_test_cartesian (Failed)
186 - vgl_test_oriented_box_2d (Failed)
307 - vgl_io_test_point_2d_io (Failed)

**Comment by dstoup** [comment]
Shame I came so late to this party. I agree with @decrispell .. we use vpgl extensively. Our vxl configurations used to build but now are broken as of last night.

**Comment by hjmjohnson** [comment]
@dstoup That was not the intention!   This PR has only 2 changes:

 if( EXISTS ${CMAKE_CURRENT_LIST_DIR}/contrib/CMakeLists.txt )
-  CMAKE_DEPENDENT_OPTION(BUILD_CONTRIB "Build the contributed libraries?" ON "BUILD_CORE_GEOMETRY;BUILD_CORE_NUMERICS;BUILD_CORE_UTILITIES;BUILD_CORE_SERIALISATION;BUILD_CORE_IMAGING" OFF)
+  CMAKE_DEPENDENT_OPTION(BUILD_CONTRIB "Build the contributed libraries?" OFF "BUILD_CORE_GEOMETRY;BUILD_CORE_NUMERICS;BUILD_CORE_UTILITIES;BUILD_CORE_SERIALISATION;BUILD_CORE_IMAGING" OFF)
   add_subdirectory(contrib)
 endif()
 
diff --git a/core/CMakeLists.txt b/core/CMakeLists.txt
index fe4c0e4788..b6af7c2591 100644
--- a/core/CMakeLists.txt
+++ b/core/CMakeLists.txt
@@ -123,7 +123,7 @@ endif()
 
 
 # video
-CMAKE_DEPENDENT_OPTION (BUILD_CORE_VIDEO "Build VXL's core video libraries" ON
+CMAKE_DEPENDENT_OPTION (BUILD_CORE_VIDEO "Build VXL's core video libraries" OFF
                         "BUILD_CORE_UTILITIES;BUILD_CORE_IMAGING" OFF)
 if (BUILD_CORE_VIDEO)

It was intended to turn off the BUILD_CORE_VIDEO which is spewing out a ton of deprecation warnings and CONTRIB which is spewing out just a ton of warnings, and has several tests failing.

Please let me know if I screwed this up.

PS:  Have a look at the dashboard today!  It's not a complete failure!

Again sorry.

Hans

**Comment by hjmjohnson** [comment]
@dstoup Do you need the  CORE_VIDEO too?

**Comment by hjmjohnson** [comment]
@dstoup I'd like to fix/revert so that your workflow is not interrupted.  Can you please confirm that both of these features need to be turned back on for your builds to work?

Thanks,
Hans

**Pull request merged**
