### PR TITLE
Large disparity

### PR DESCRIPTION
**Pull request by mundyj**
## PR Checklist

:no_entry_sign: --> Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
 :no_entry_sign: --> Makes design changes to existing vxl/core\* API that requires semantic versioning increase

-  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
 :no_entry_sign: --> Adds tests and baseline comparison (quantitative).
:no_entry_sign: --> Adds Documentation.

### CODE REVIEW

**Comment by mundyj** [comment]
bsgm was not searching over a large enough disparity range and required per-pixel initial guess as to the minimum start to the search. The existing capability for dense min-disparity is now working successfully. Also a function was added that finds the min and max disparity limits for a specified min and max height. The limits are found using the target and reference cameras

**Review by drewgilliam — CHANGES_REQUESTED** [review]
Many debug statements that save to hardcoded windows paths are still present, please remove.

**Comment by hjmjohnson** [comment]
@mundyj   Please squash the commits to that bugs are not added and removed in a single patch.

**Review by drewgilliam — APPROVED** [review]
@hjmjohnson - @mundyj has squashed, should be good

**Pull request merged**
