### PR TITLE
vgl fixes

### PR DESCRIPTION
**Pull request by decrispell**
some fixes for warnings, compiler errors, and test errors in vgl

### CODE REVIEW

**Comment by decrispell** [comment]
Yes, I will work on knocking those out as well.  We can until all tests are passing before merging.

**Comment by hjmjohnson** [comment]
@decrispell THANKS!  I'll wait until all tests are passing and then merge. This is a great help.

**Comment by decrispell** [comment]
@hjmjohnson The CI builds look clean now.

**Comment by hjmjohnson** [comment]
@decrispell Thank you!  This is AWESOME.  It will save me many, many hours of frustration.

I'm trying to keep VXL alive and well!

**Comment by decrispell** [comment]
No problem @hjmjohnson , thanks for keeping an eye on vxl 👍

**Pull request merged**
