### PR TITLE
Update to require c make289

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@thewtex @decrispell @dstoup @TimCootes 

I'd like to update cmake to 2.8.9 to avoid bugs in 2.8.7 that would require a lot of work arounds.

Does anyone have an objection to this?

Hans

**Comment by hjmjohnson** [comment]
The 1 test failure from clang is a test that often fails and is unrelated to this patch.

**Comment by hjmjohnson** [comment]
@thewtex Thanks for the review Matt.  If I don't hear any objections, I'll merge soon.

Hans

**Comment by dstoup** [comment]
Looks good to me!

**Pull request merged**
