### PR TITLE
Perspective ambiguity

### PR DESCRIPTION
**Pull request by mundyj**
## PR Checklist

- :no_entry_sign: --> Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
- :no_entry_sign: --> Makes design changes to existing vxl/core\* API that requires semantic versioning increase

-  [X] or  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
-  :no_entry_sign: --> Adds tests and baseline comparison (quantitative).
- :no_entry_sign: --> Adds Documentation.

### CODE REVIEW

**Comment by decrispell** [comment]
@hjmjohnson Any idea what could be causing the lack of communication between travis-ci and github?  The tests appear to be running, but not reporting back.

https://travis-ci.org/github/vxl/vxl/pull_requests?utm_medium=notification&utm_source=github_status

**Comment by hjmjohnson** [comment]
@decrispell Sorry no idea.  I do not have administrative access to vxl.

**Comment by decrispell** [comment]
@hjmjohnson  Oh, sorry - I thought you did.  @mleotta, any idea?

**Comment by mleotta** [comment]
@decrispell Try to restart this one.  I followed the instructions here:

https://github.com/travis-ci/travis-ci/issues/10204

and I removed the deprecated "continuous-integration/travis-ci" option.  Maybe that will help, but it's a shot in the dark.

**Comment by mundyj** [comment]
See if travis picks up this time

**Pull request closed without merging**
