### PR TITLE
BUG: remove lsqr because of license issues ITK 1160

### PR DESCRIPTION
**Pull request by QuadmasterXLII**
In 2010 Luis Ibanez noticed that ITK used code under an
incompatible license to solve sparse linear systems. He
replaced that code by porting a BSD licensed sparse solver
written in fortran (available at
http://www.stanford.edu/group/SOL/software.html) to C++.
However, this effort was lost during the refactoring for
ITK 4. This commit replaces the incompatibly licensed code with Luis's port.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
👍 
@thewtex Could you have a look at this to ensure that this change will also merge well with ITK?

**Comment by thewtex** [comment]
@QuadmasterXLII @hjmjohnson overall this looks good, but a new revision should be submitted with the latest version from http://review.source.kitware.com/#/c/21296/

**Comment by thewtex** [comment]
CC: @tvercaut

**Comment by hjmjohnson** [comment]
@QuadmasterXLII  Will you be able to syncronize this patch set with the content from  http://review.source.kitware.com/#/c/21296/? 

If not, please let us know so that someone else can be assigned to do this.  Thank you, Hans.

**Comment by QuadmasterXLII** [comment]
@hjmjohnson done at https://github.com/vxl/vxl/pull/337

**Pull request closed without merging**
