### PR TITLE
Wip new travis with docker

### PR DESCRIPTION
**Pull request by ajjl**
WIP
WIP
I've never worked with travis before, so I'm just trying some things out.

### CODE REVIEW

**Comment by ajjl** [comment]
@hjmjohnson Please, do not merge! Sorry, I should have been more clear. I am trying to test the travisCI system and I'm not sure how to get it to trigger a build without making a pull request. Is there a better way to do this?

**Comment by hjmjohnson** [comment]
Andrew,

Just squash all those commits.  Every new commit (even if it’s not a new patch) will trigger a build.”

Hans

--

**Comment by ajjl** [comment]
Sounds good. I'll close the request.

**Comment by hjmjohnson** [comment]
@ajj

**Comment by hjmjohnson** [comment]
@ajjl You do not need to close the request, just squash the patches into something more meaningful, then force push a new version of this branch.

**Pull request closed without merging**
