### PR TITLE
Remove unused `.dsptemplate` files

### PR DESCRIPTION
**Pull request by bradking**
These files were needed only for the CMake VS 6 generator that we
no longer support.

### CODE REVIEW

**Comment by bradking** [comment]
Cc: @thewtex

**Comment by bradking** [comment]
Cc: @hjmjohnson

**Comment by hjmjohnson** [comment]
Deleted code is easy to maintain!  Thank you for noticing.

**Comment by thewtex** [comment]
+1 Thanks!

**Pull request merged**
