### PR TITLE
Raphael Kargon Summer 2017 Work (Multi-BSTM)

### PR DESCRIPTION
**Pull request by andyneff**
PR for adding work to vxl main repo

@rkargon @deuscovrigus

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@rkargon @deuscovrigus @andyneff 

A longer description is needed for inclusion of these patches.  What is the audience that needs these patches?  Who is going to maintain this part of the code tree?  Has anyone else verified that these commits will work with other peoples code base?

I'd like to either commit or reject this very large set of changes soon.

**Comment by deuscovrigus** [comment]
This work is a collection of development that me and Osman Ulusoy
contributed to bomx2 and bstm . The library adds more support and
functionality to building voxel worlds and time varying voxel worlds using
imagery or silhuette imagery. In addition this adds support for refining
such scenes based on probability or improvements to the current refine
codes. FInally, the bstm library has a feature added for a more efficient
partitioning.

-Octavian

**Comment by decrispell** [comment]
I will review with @deuscovrigus .

**Comment by hjmjohnson** [comment]
@decrispell Thanks.  Trying to keep contributions moving!

**Comment by decrispell** [comment]
Failing test (rgrl_registration_blackbox) seem to be spurious.

**Comment by hjmjohnson** [comment]
@decrispell Thank you for shepherding this MR.  There was a change to the travis build environment that causes the built environment to fail.    This pull request will need a rebase to allow travis to test the environment.

**Comment by andyneff** [comment]
@decrispell the .bin files should be removed now

**Comment by decrispell** [comment]
LGTM.  We can add replacements for the tests that were removed at a later time.  I don't think it's worth holding up the whole PR for that.

**Comment by hjmjohnson** [comment]
LGTM too.  This should not impact the core of ITK, but is mostly related to contrib directories.

**Comment by hjmjohnson** [comment]
@decrispell  Please merge when you are ready.

**Pull request merged**
