### PR TITLE
VSI 2017 Public release

### PR DESCRIPTION
**Pull request by andyneff**
The last year's worth of work on VXL has been given the green light for public release.

Includes development in the BRL projects, bug fixed, updating v3p clipper

@decrispell @yidongVSI @mundyj @drewgilliam

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@andyneff See #442  for the same code changes, but in an easier to review format.  This set of changes can be merged if reviewing #442 is approved.

**Comment by hjmjohnson** [comment]
@andyneff This branch conflicts with recent 1-year commits.  Please rebase to resolve conflicts.

**Comment by andyneff** [comment]
Ok, I've cleaned up the last little merge errors, and reproduced the same WIP_REVIEW view in https://github.com/VisionSystemsInc/vxl/commits/WIP_REVIEW

**Comment by andyneff** [comment]
@hjmjohnson Is there anything else you need for this PR?

**Comment by hjmjohnson** [comment]
@andyneff 
1) This is cover part of "contrib" code base that I never use, so I'd rather have some approval of those people who these changes would affect.  

Hans

**Comment by hjmjohnson** [comment]
@andyneff @decrispell Are any issues on the issue tracker addressed by this huge merge?

**Comment by andyneff** [comment]
Are #71, #80, and #54 still relevant?

**Pull request merged**
